### PR TITLE
Upgrade Gradle to Version `8.11.1` and Refactor Deprecated Code

### PR DESCRIPTION
**Pull request by furqoncreative**
# Proposed Changes

- **Upgrade Gradle Version:**
 Update the Gradle version to 8.11.1 to leverage the latest features and improvements, as well as to ensure compatibility with newer Java versions.

- **Refactor Code:**
Refactor portions of the codebase to replace deprecated features and methods introduced in the new Gradle version. This ensures that the project remains up-to-date and maintains optimal functionality.

### CODE REVIEW

**Comment by arifaizin** [comment]
di aku, ketika jalanin gradle test, munculnya hanya 
image

beda seperti sebelumnya yang nampilin error di tiap latihan-nya. Memang seperti itukah?

**Comment by arifaizin** [comment]
Ini kalau yang sebelumnya
image

**Comment by furqoncreative** [comment]
Oh iya ada error karena salah pas get build directory Mas @arifaizin. Sekarang harusnya udah resolve.

**Comment by arifaizin** [comment]
Okee, dariku sudah aman yah @furqoncreative 
Sorry baru cek 🙏

**Review by alfianyusufabdullah — APPROVED** [review]
dariku aman ya @furqoncreative .

**Comment by furqoncreative** [comment]
Minta tolong di-merge kalau sudah aman ya Mas @alfianyusufabdullah

**Pull request merged**
